import { nanoid } from "@reduxjs/toolkit";

const Items = [
  {
    id: nanoid(),
    name: "react",
    checked: false,
    show: false,
    img: "/assets/react.png",
  },
  {
    id: nanoid(),
    name: "react",
    checked: false,
    show: false,
    img: "/assets/react.png",
  },
  {
    id: nanoid(),
    name: "css",
    checked: false,
    show: false,
    img: "/assets/css.png",
  },
  {
    id: nanoid(),
    name: "css",
    checked: false,
    show: false,
    img: "/assets/css.png",
  },
  {
    id: nanoid(),
    name: "html",
    checked: false,
    show: false,
    img: "/assets/html.png",
  },
  {
    id: nanoid(),
    name: "html",
    checked: false,
    show: false,
    img: "/assets/html.png",
  },
  {
    id: nanoid(),
    name: "javascript",
    checked: false,
    show: false,
    img: "/assets/js.png",
  },
  {
    id: nanoid(),
    name: "javascript",
    checked: false,
    show: false,
    img: "/assets/js.png",
  },
  {
    id: nanoid(),
    name: "nodejs",
    checked: false,
    show: false,
    img: "/assets/nodejs.png",
  },
  {
    id: nanoid(),
    name: "nodejs",
    checked: false,
    show: false,
    img: "/assets/nodejs.png",
  },
  {
    id: nanoid(),
    name: "python",
    checked: false,
    show: false,
    img: "/assets/python.png",
  },
  {
    id: nanoid(),
    name: "python",
    checked: false,
    show: false,
    img: "/assets/python.png",
  },
  {
    id: nanoid(),
    name: "redux",
    checked: false,
    show: false,
  img: "/assets/redux.png",
  },
  {
    id: nanoid(),
    name: "redux",
    checked: false,
    show: false,
    img: "/assets/redux.png",
  },
  {
    id: nanoid(),
    name: "nextjs",
    checked: false,
    show: false,
    img: "/assets/nextjs.png",
  },
  {
    id: nanoid(),
    name: "nextjs",
    checked: false,
    show: false,
    img: "/assets/nextjs.png",
  },
  {
    id: nanoid(),
    name: "tailwind",
    checked: false,
    show: false,
    img: "/assets/tailwind.png",
  },
  {
    id: nanoid(),
    name: "tailwind",
    checked: false,
    show: false,
    img: "/assets/tailwind.png",
  },
  {
    id: nanoid(),
    name: "vscode",
    checked: false,
    show: false,
    img: "/assets/vscode.png",
  },
  {
    id: nanoid(),
    name: "vscode",
    checked: false,
    show: false,
    img: "/assets/vscode.png",
  },
];

export default Items;
